title: <%= ENV["APP_TITLE"] || 'Spread Beaver' %>

latest_entries_per_feed: <%= ENV["LATEST_ENTRIES_PER_FEED"] || 3 %>
duration_for_common_stream: <%= ENV["DURATION_FOR_COMMON_STREAM"] || 4 %>
duration_for_ranking: <%= ENV["DURATION_FOR_RANKING"] || 2 %>

feedly_target: <%= ENV["FEEDLY_TARGET"] || 'sandbox' %>

twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>

youtube_data_api_key:  <%= ENV["YOUTUBE_DATA_API_KEY"] %>
soundcloud_client_id:  <%= ENV["SOUNDCLOUD_CLIENT_ID"] %>

spotify_client_id:     <%= ENV['SPOTIFY_CLIENT_ID'] %>
spotify_client_secret: <%= ENV['SPOTIFY_CLIENT_SECRET'] %>
spotify_callback_url:  <%= ENV['SPOTIFY_CALLBACK_URL'] || "typica://callback" %>

spotify_playlist_updaters:
  name:
    email: "email@xxx.com"
    mix_playlists:
      id:
        topic: "topic/xxx"
        name: "Top 100"
twitter_bots:
  name:
    email: "email@xxx.com"
    locale: "ja"
    topic: "topic/xxx"
